### ISSUE TITLE
Switch to Getthermostatsdata, Gethomedata and Getstationsdata by November 30th.

### ISSUE THREAD

**Issue by patricks** [karbassi/netatmo#20]
I got this email today:

Friendly reminder: Getthermstate, Getuser and Devicelist will move from deprecated to shut down. On November 30th, we are proceeding to a structural change to make our APIs faster and more powerful. Unfortunately, old and deprecated API methods won’t be supported anymore. Make sure you amend your code and start using newer methods as soon as possible for a smooth transition:
- Replace Getthermstate with Getthermostatdata
- Replace Getuser with Getthermostatdata, Gethomedata or Getstationsdata
- Replace Devicelist with Getthermostatdata or Getstationsdata

So it looks like, there are some updates for the library required.

**Comment by danilowanner** [comment]
Hi @patricks 

Thanks for the notification. Will you be able to implement some (all?) of the changes? I might be able to help out if necessary.

@karbassi: Are you planning on updating the package yourself or would you welcome pull requests that switch to the new APIs?

Best
Danilo

**Comment by karbassi** [comment]
@danilowanner and @patricks I would gladly accept PRs!

**Comment by danilowanner** [comment]
@patricks @karbassi I will invest some time later today to implement the changes. So far nobody else has done it, right?
