### ISSUE TITLE
Webpack issue with 'fs' module

### ISSUE THREAD

**Issue by Wifsimster** [karbassi/netatmo#24]
I'm very grateful for this module :+1: 

Just to help people out, if you use webpack and have this issue :

```
ERROR in ./~request/lib/bar.js
Module not found: Error: Cannot resolve module 'fs' in [..]
```

You need to add this to your **webpack.config** :
```
node: {
  fs: "empty"
}
```
Cf. https://github.com/josephsavona/valuable/issues/9

**Comment by karbassi** [comment]
@Wifsimster is there anything that I need to update with the `netatmo` lib? Reading it, it seems like it's mainly a webpack issue. Is it true?
