### ISSUE TITLE
Mobile app desync

### ISSUE THREAD

**Issue by nekloth** [karbassi/netatmo#25]
I'm using your package through a node-red netamo package (fork of ssadams11).

As soon as the node calls the API, the mobile app loose the connection ("Your Netamo Relay is not connected anymore to our servers. Did you change the wifi password or unplugged the relay ?")^.

To "connect" it again, I have to set a new temperature thanks to the module itself (physically).

**Comment by karbassi** [comment]
@nekloth I don't believe this is an issue with this API. Check in with @ssadams11
