### ISSUE TITLE
Include the setpoint_temp parameter in setThermpoint method

### ISSUE THREAD

**Issue by nekloth** [karbassi/netatmo#26]
As mentioned in the documentation (https://dev.netatmo.com/dev/resources/technical/reference/thermostat/setthermpoint) **setpoint_temp** parameter let you select the desired temperature, in _manual_ **setpoint_mode**.

It is not part of the current method:
```
  var form = {
    access_token: access_token,
    device_id: options.device_id,
    module_id: options.module_id,
    setpoint_mode: options.setpoint_mode,
};
```

**Comment by nekloth** [comment]
Hum ... I added this on **line 521** of _netatmo.js_:
`setpoint_temp: options.setpoint_temp,`

... and it does the job.

... but I'm not familiar at all with Github. Can you integrate it ?

**Comment by karbassi** [comment]
Hello @nekloth,

Thanks for reaching out.

What you're asking about is already part of the code. Please take a look at the **[examples](https://github.com/karbassi/netatmo/blob/v2.0.0/README.md#example-1)** in the [README](https://github.com/karbassi/netatmo/blob/v2.0.0/README.md) file for examples of what you're looking to do.

What you're looking to do is:

```node
// Set Thermpoint
// See docs: https://dev.netatmo.com/dev/resources/technical/reference/thermostat/setthermpoint
var options = {
  device_id: '',
  module_id: '',
  setpoint_mode: '',
};

api.setThermpoint(options, function(err, status) {
  console.log(status);
});
```

In this example, you need to make sure you fill in your `options` variable, as the example sets them to nothing.

– Ali

**Comment by nekloth** [comment]
I'm sorry to insist, but no, it is not part of the code...

In the Netatmo documentation (link you shared), there are 6  parameters for the endpoint _https://api.netatmo.com/api/setthermpoint_:
* token 
* device_id
* module_id
* setpoint_mode
* setpoint_temp (description from the doc : _If setpoint_mode is manual, returns the temperature setpoint in °C._)

The last one allows to set a temperature which is not in a program. 
This value is taken into account when the `setpoint_mode` parameter is set to `"MANUAL"`

In the examples you linked, and the one you copied, there is no parameter for the temperature itself, just the mode.

So please, do not close this request.

**Comment by karbassi** [comment]
Can you test to see if this works for you:

```node
var options = {
  device_id: '',
  module_id: '',
  setpoint_mode: '',
  setpoint_temp: '',
};

api.setThermpoint(options, function(err, status) {
  console.log(status);
});
```

Please fill in the values inside `options`.

**Comment by nekloth** [comment]
Hum. I apologize. I must have made a wrong first usage. It works.

Maybe you can add the setThermPoint usage example in the README ?

By the way, thank you for your time and quick answer and sorry for the disturbance.
