### ISSUE TITLE
Error: Authentication error: No response

### ISSUE THREAD

**Issue by cflurin** [karbassi/netatmo#29]
Starting last night at 03:00 I'm getting this error message:
```sh
"Error: Authentication error: No response"
```
Is anyone experiencing the same issue?

**Comment by cflurin** [comment]
It works again without any changes. I suppose there was an issue with the server.

**Comment by skrollme** [comment]
I sometimes get this, too. But then, it do not work for at least 1 or 2 days. Could this be a API-Limit problem? Too many request per time?

**Comment by karbassi** [comment]
@skrollme it could be. The code returns `No response` when the server sends nothing back but with an error status.

If this happens to you again, could you catch the server response to the format of the response. I've noticed inconsistent API patterns with this API.

**Comment by skrollme** [comment]
I will give my best, @karbassi. After the last "soft ban" I reduced the apps which were allowed to access my netatmo-account. IFTTT, WeatherUnderground, MacToolbar-Widget, ... all gone.

**Comment by cflurin** [comment]
Currently I'm facing this error often again. 
I'm using https://github.com/guidone/node-red-contrib-netatmo-dashboard (dependency: netatmo).

**Comment by skrollme** [comment]
It seems that there are some server problems at netatmo's api (see their support-account at twitter). For me its sometimes working, sometimes not...

**Comment by cflurin** [comment]
It's quite annoying. I'm working on the node-red-node in order to handle this error properly.

**Comment by skrollme** [comment]
@karbassi I can currently reproduce the problem:

```
pi@raspberrypi:~/nodetest $ node test.js 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Authenticate error: No response
    at netatmo.handleRequestError (/home/pi/nodetest/node_modules/netatmo/netatmo.js:46:15)
    at netatmo.<anonymous> (/home/pi/nodetest/node_modules/netatmo/netatmo.js:115:19)
    at self.callback (/home/pi/nodetest/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/pi/nodetest/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
```

The response - right before calling _this.handleRequestError_ - is _undefined_ when logged via `console.log(response)`

The case was reproduced via an simple test-script:
```
var netatmo = require('netatmo');

var auth = {
	"client_id": "123456789",
	"client_secret": "12345678901234567890",
	"username": "mail@me",
	"password": "password"
};

var api = new netatmo(auth);

api.getStationsData(function(err, devices) {
  console.log(devices);
});
```

**Comment by cflurin** [comment]
@skrollme 
have a look here: https://github.com/karbassi/netatmo#catching-errors-and-warnings

**Comment by skrollme** [comment]
@karbassi thanks, I will try it next time the problem occurs. currently the netatmo api works for me again.

**Comment by karbassi** [comment]
Glad it's all been straightened out. 👍 😄

**Comment by skrollme** [comment]
I got an answer from Netatmo Support to my questions about possible soft bans, API limits, and so on. Besides the [Rate Limits](https://dev.netatmo.com/resources/technical/guides/ratelimits) page you probably already know he writes this. Just in case you are interested:

> ...
> and yes, your IP address could get banned for 24h, if it exceeded 30 requests that tend to 4xx errors within a minute. In order to solve this issue, we advise to follow the recommendations below:
> - Spread your user requests, do not make all your request at the same time every X minutes. Spread the load per user.
> - When you do a Oauth2, you receive an expires_in value that tell you when the token expires. With this information, you will have to anticipate and refresh the token before doing any requests.
> - If an error 4xx is received please make sure not to repeat the request, rather show an error message in the App in order to correct this issue before redoing the request.

**Comment by paaland** [comment]
Seems to me they have been having problems with one of their servers.

```
$nslookup api.netatmo.net
Name:    api.netatmo.net
Addresses:  195.154.172.147
          195.154.179.238
```
They seem to rely on DNS round-robin to handle load balancing. The problem is that when the first server is down the netatmo node package does not continue and try the next one. This actually seems to be an issue with node as it caches the DNS lookup and keeps trying the first IP forever.

wget and curl goes on and tries the next one if the first does not work. If you could build some sort of error handling that goes on to the next server in your API that would be great.

**Comment by cflurin** [comment]
I'm receiving two error messages:
```sh
Authenticate error: Status code503"
```
and
```sh
getStationsDataError error: Status code503
```
The interval is 5 minutes!

**Comment by karbassi** [comment]
@skrollme I'd welcome a PR for throttling API requests. Such as limiting the SDK to make `X` API requests in `Y` seconds. 

E.g.: `10 requests in 1 minute`.

@paaland Could you submit a PR with your suggested changes for me to look at?
